WebApplication1/Controllers/AnimalController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class AnimalController : Controller
    {
        private ApplicationContext _context;

        private readonly ILogger<AnimalController> _logger;
        IWebHostEnvironment _appEnvironment;

        public AnimalController(ILogger<AnimalController> logger, ApplicationContext context, IWebHostEnvironment appEnvironment)
        {
            _logger = logger;
            _context = context;//db
            _appEnvironment = appEnvironment;
        }
        //Animals
        public async Task<IActionResult> Animals()
        {
            return View(await _context.Animals.ToListAsync());
        }
        public IActionResult CreateAnimal()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CreateAnimal(Animal animal, IFormFile uploadedFile)
        {

            string fileName = uploadedFile.FileName;
            if (uploadedFile != null)
            {

                string path = "/images/animals/" + fileName;
                // сохраняем файл в папку Files в каталоге wwwroot
                using (var fileStream = new FileStream(_appEnvironment.WebRootPath + path, FileMode.Create))
                {
                    await uploadedFile.CopyToAsync(fileStream);
                }

            }
            animal.Image = fileName;
            _context.Animals.Add(animal);
            await _context.SaveChangesAsync();
            return RedirectToAction("Animals");
        }
        public async Task<IActionResult> EditAnimal(int? id)
        {
            if (id != null)
            {
                Animal animal = await _context.Animals.FirstOrDefaultAsync(p => p.Id == id);
                if (animal != null)
                    return View(animal);
            }
            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> EditAnimal(Animal animal, IFormFile uploadedFile)
        {
            if (uploadedFile != null)
            {
                string fileName = uploadedFile.FileName;
                if (animal.Image != fileName)
                {
                    animal.Image = fileName;
                    string path = "/images/animals/" + fileName;
                    // сохраняем файл в папку Files в каталоге wwwroot
                    using (var fileStream = new FileStream(_appEnvironment.WebRootPath + path, FileMode.Create))
                    {
                        await uploadedFile.CopyToAsync(fileStream);
                    }
                }

            }

            _context.Animals.Update(animal);
            await _context.SaveChangesAsync();
            return RedirectToAction("Animals");
        }
        [HttpGet]
        [ActionName("DeleteAnimal")]
        public async Task<IActionResult> ConfirmDelete(int? id)
        {
            if (id != null)
            {
                Animal animal = await _context.Animals.FirstOrDefaultAsync(p => p.Id == id);
                if (animal != null)
                    return View(animal);
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> DeleteAnimal(int? id)
        {
            if (id != null)
            {
                Animal user = new Animal { Id = id.Value };
                _context.Entry(user).State = EntityState.Deleted;
                await _context.SaveChangesAsync();
                return RedirectToAction("Animals");
            }
            return NotFound();
        }


    }
}

WebApplication1/Controllers/TeamMemberController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Composition;
using System.Diagnostics;
using System.Drawing;
using System.IO;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class TeamMemberController : Controller
    {
        private ApplicationContext _context;
        IWebHostEnvironment _appEnvironment;
      
        private readonly ILogger<TeamMemberController> _logger;

        public TeamMemberController(ILogger<TeamMemberController> logger, ApplicationContext context, IWebHostEnvironment appEnvironment)
        {
            _logger = logger;
            _context = context;//db
            _appEnvironment = appEnvironment;
        }
        //Team 
        public async Task<IActionResult> Team()
        {
            return View(await _context.TeamMembers.ToListAsync());
        }
        public IActionResult CreateTeamMember()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CreateTeamMember(TeamMember teamMember, IFormFile uploadedFile)
        { 
            string fileName= uploadedFile.FileName;
            if (uploadedFile != null)
            {

                string path = "/images/team/" + fileName;
                // сохраняем файл в папку Files в каталоге wwwroot
                using (var fileStream = new FileStream(_appEnvironment.WebRootPath + path, FileMode.Create))
                {
                    await uploadedFile.CopyToAsync(fileStream);
                }

            }
            teamMember.Image = fileName;
            _context.TeamMembers.Add(teamMember);
            await _context.SaveChangesAsync();
            return RedirectToAction("Team");
        }
        public async Task<IActionResult> EditTeamMember(int? id)
        {
            if (id != null)
            {
                TeamMember teamMember = await _context.TeamMembers.FirstOrDefaultAsync(p => p.Id == id);

                

                if (teamMember != null)
                    return View(teamMember);
            }
            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> EditTeamMember(TeamMember teamMember, IFormFile uploadedFile)
        {
            if (uploadedFile != null)
            {
                string fileName = uploadedFile.FileName;
                if (teamMember.Image != fileName)
                {
                    teamMember.Image = fileName;
                    string path = "/images/team/" + fileName;
                    // сохраняем файл в папку Files в каталоге wwwroot
                    using (var fileStream = new FileStream(_appEnvironment.WebRootPath + path, FileMode.Create))
                    {
                        await uploadedFile.CopyToAsync(fileStream);
                    }
                }

            }
            _context.TeamMembers.Update(teamMember);

            await _context.SaveChangesAsync();
            return RedirectToAction("Team");
        }
        [HttpGet]
        [ActionName("DeleteTeamMember")]
        public async Task<IActionResult> ConfirmDeleteTeamMember(int? id)
        {
            if (id != null)
            {
                TeamMember teamMember = await _context.TeamMembers.FirstOrDefaultAsync(p => p.Id == id);
                if (teamMember != null)
                    return View(teamMember);
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> DeleteTeamMember(int? id)
        {
            if (id != null)
            {
                TeamMember teamMember = new TeamMember { Id = id.Value };
                _context.Entry(teamMember).State = EntityState.Deleted;
                await _context.SaveChangesAsync();
                return RedirectToAction("Team");
            }
            return NotFound();
        }

       

    }
}

WebApplication1/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity;
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <div class="header-content">
        <nav >
             
           
                    <ul class="navig">
                        <li>
                            <a class ="logo" asp-area="" asp-controller="Home" asp-action="Index">ShapShelter</a>
                        </li>
                        <li >
                            <a asp-area="" asp-controller="Animal" asp-action="Animals">Животные</a>
                        </li>
                        <li >
                        <a asp-area="" asp-controller="TeamMember" asp-action="Team">Команда</a>
                        </li>
                    @if (!SignInManager.IsSignedIn(User))
                    {
                        <li >
                            <a  asp-area="" asp-controller="Home" asp-action="Contact">О нас</a>
                        </li>
                  }
                    </ul>



                <partial name="_LoginPartial" />

                    </nav>
                    
                
                    
               
        </div>
       
      
    </header>
    <div class="container">
        <main role="main" >
            @RenderBody()
        </main>
    </div>

    <footer >
        <div class="footer-data">
            &copy; 2023 - ShapShelter - Belarus
        </div>
    </footer>
 
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>